spring:
  application:
    name: AnyNoteApi
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ZmFraXNkZmFrc2RmYWtzZGZha3NkZmFrc2RmYQ==
  expiration: 604800
  refresh-expiration: 2592000

rate-limit:
  rules:
    - path: /login
      capacity: 5
      duration: 60
